function scene = generateGaborScene(stimParams)
% Method to generate an ISETBio scene of a Gabor stimulus with given params.
% We will use a built-in scene generation method in ISETBio which generates
% sinusoidal images. This function requires a params struct which we generate
% below based on the passed stimuParams info
imageHarmonicParams = struct(...
        'freq', stimParams.sizeDegs * stimParams.spatialFrequencyCyclesPerDeg, ...
        'ang', stimParams.orientationDegs/180*pi, ...
        'ph', stimParams.phaseDegs/180*pi, ...
        'contrast', stimParams.contrast, ...
        'GaborFlag', stimParams.sigmaDegs/stimParams.sizeDegs, ...
        'row', stimParams.pixelsAlongHeightDim , ...
        'col', stimParams.pixelsAlongWidthDim);
    
% Generate a scene using these params
scene = sceneCreate('harmonic', imageHarmonicParams);

% Match viewing distance and mean luminance params
scene = sceneSet(scene, 'wangular', stimParams.sizeDegs);
scene = sceneAdjustLuminance(scene, stimParams.meanLuminanceCdPerM2);
end