function t_treeShrewConeMosaic()
% Generate treeshrew cone mosaic
%
% Description:
%   Generates a treeshrew cone mosaic

% History:
%    02/28/26  NPC  Wrote it.

  
     theConeMosaic = cMosaicTreeShrewCreate(...
        'sizeDegs', [2 2], ...
        'integrationTimeSeconds', 100/1000);


     theOI = oiTreeShrewCreate( ...
            'opticsType', 'wvf', ...
            'pupilDiameterMM', 4.0, ...
            'whichShrew', 1, ...
            'name', 'wvf-based optics');

     % Get the optics data
     optics = oiGet(theOI, 'optics');

     theVisualizedWavelength = 550;
     wavelengthSupport = opticsGet(optics, 'otf wave');
     [~,theVisualizedWavelengthIndex] = min(abs(wavelengthSupport-theVisualizedWavelength));

     % Get the psf data
     psf = opticsGet(optics, 'psf data');

     thePSFdataStruct = struct(...
            'supportXmicrons', squeeze(psf.xy(1,:,1)), ...
            'supportYmicrons', squeeze(psf.xy(:,2,2)), ...
            'data', squeeze(psf.psf(:,:,theVisualizedWavelengthIndex)) ...
            );


    hFig = figure(1);
    clf;
    domainUnits = 'microns';

    load(fullfile(ISETTreeShrewRootDirectory, 'data', 'coneMosaicPhotoFromMullerEtAl1989.mat'), 'theConeMosaicImage', 'sampleSpacingMicrons');
    rows = size(theConeMosaicImage,1);
    cols = size(theConeMosaicImage,2);
    spatialSupportX = (1:cols)*sampleSpacingMicrons;
    spatialSupportY = (1:rows)*sampleSpacingMicrons;
    spatialSupportX = spatialSupportX-mean(spatialSupportX(:));
    spatialSupportY = spatialSupportY-mean(spatialSupportY(:));
    ax = subplot(2,2,1);
    image(ax, spatialSupportX, spatialSupportY, theConeMosaicImage);
    axis(ax, 'image')
    set(ax, 'XTick', -60:30:60, 'YTick', -60:30:60, 'XLim', [-60 60], 'YLim', [-60 60]);
    set(ax, 'FontSize', 16);
    xlabel(ax, 'eccentricity (microns)')
    ylabel(ax, 'eccentricity (microns)')
    title(ax, 'S-cone stained whole-mount retina of the TreeShrew (Fig. 3 from Muller et al (1989)');

    ax = subplot(2,2,2);
    domainVisualizationTicks = struct(...
            'x',  sign(theConeMosaic.eccentricityMicrons(1)) * round(abs(theConeMosaic.eccentricityMicrons(1))) + 30*(-2:2), ...
            'y',  sign(theConeMosaic.eccentricityMicrons(2)) * round(abs(theConeMosaic.eccentricityMicrons(2))) + 30*(-2:2));

    activation = zeros(1,1,theConeMosaic.conesNum);
    activation(1,1,theConeMosaic.lConeIndices) = activation(1,1,theConeMosaic.lConeIndices) + 0.7;
    activation(1,1,theConeMosaic.sConeIndices) = activation(1,1,theConeMosaic.sConeIndices) + 0.2;
    theConeMosaic.visualize('figureHandle', hFig, ...
            'axesHandle', ax, ...
            'domain', domainUnits, ...
            'domainVisualizationTicks', domainVisualizationTicks, ...
            'domainVisualizationLimits', [-60 60 -60 60], ...
            'visualizedConeAperture', 'lightcollectingarea4sigma', ...
            'activation', activation, ...
            'activationRange', [0 1], ...
            'activationcolormap', brewermap(256, '*greys'), ...
            'visualizedConeApertureThetaSamples', 32, ...
            'conesAlpha', 0.8, ...
            'conesEdgeAlpha', 0.9, ...
            'backgroundColor', [1 1 1], ...
            'clearAxesBeforeDrawing', false, ...
            'plotTitleColor', [0.5 0.5 0.5], ...
            'fontSize', 16, ...
            'verbose', false, ...
            'plotTitle', 'ISETBio model of tree shrew cone mosaic', ...
            'plotTitleFontSize', 16 ...
            );

    % Visualize part of the mosaic
    psfPlotHalfWidthMicrons = 15;
    domainVisualizationLims(1:2) = theConeMosaic.eccentricityMicrons(1) + (psfPlotHalfWidthMicrons+0.5)*[-1 1];
    domainVisualizationLims(3:4) = theConeMosaic.eccentricityMicrons(2) + (psfPlotHalfWidthMicrons+0.5)*[-1 1];
    domainVisualizationTicks = struct(...
            'x',  sign(theConeMosaic.eccentricityMicrons(1)) * round(abs(theConeMosaic.eccentricityMicrons(1))) + psfPlotHalfWidthMicrons*[-1 0 1], ...
            'y',  sign(theConeMosaic.eccentricityMicrons(2)) * round(abs(theConeMosaic.eccentricityMicrons(2))) + psfPlotHalfWidthMicrons*[-1 0 1]);


    ax = subplot(2,2,3);
    theConeMosaic.visualize('figureHandle', hFig, ...
            'axesHandle', ax, ...
            'domain', domainUnits, ...
            'visualizedConeAperture', 'lightCollectingAreaCharacteristicDiameter', ...
            'visualizedConeApertureThetaSamples', 32, ...
            'domainVisualizationLimits', domainVisualizationLims, ...
            'domainVisualizationTicks', domainVisualizationTicks, ...
            'activation', activation, ...
            'activationRange', [0 1], ...
            'withSuperimposedPsf', thePSFdataStruct, ...
            'withSuperimposedPSFcontourLineColor', [1 0 0], ...
            'activationColorMap', brewermap(256, '*greys'), ...
            'noYLabel', false, ...
            'noXlabel', false, ...
            'backgroundColor', [1 1 1], ...
            'clearAxesBeforeDrawing', false, ...
            'plotTitleColor', [0.5 0.5 0.5], ...
            'fontSize', 16, ...
            'verbose', false, ...
            'plotTitle', 'ISETBio model of tree shrew cone mosaic and optics', ...
            'plotTitleFontSize', 16 ...
            );


    theTreeShrewLens = lensTreeShrewCreate('wave', theConeMosaic.wave);
    plotConeQuantalEfficiencies(theConeMosaic, theTreeShrewLens);

end





function plotConeQuantalEfficiencies(theConeMosaic, theLens)

    lambda = theConeMosaic.wave;
    
    efficienciesAtCornea = ~true;
    
    if (efficienciesAtCornea)
        for iConeType = cMosaic.LCONE_ID : cMosaic.SCONE_ID
            quantalEfficiencies(:,iConeType) = theConeMosaic.qe(:,iConeType)  .* theLens.transmittance;
        end
    else
        for iConeType = cMosaic.LCONE_ID : cMosaic.SCONE_ID
            quantalEfficiencies(:,iConeType) = theConeMosaic.qe(:,iConeType)  .* theConeMosaic.macular.transmittance;
        end
    end
    

    xLims = [lambda(1) lambda(end)];
    yLims = [0 0.05];
    xTicks = 400:50:850;
    yTicks = 0:0.1:1;
    
    hFig = figure(11);
    plot(lambda, quantalEfficiencies(:,cMosaic.LCONE_ID), 'r-', 'LineWidth', 1.5);
    hold on;
    plot(lambda, quantalEfficiencies(:,cMosaic.MCONE_ID), 'g-',  'LineWidth', 1.5);
    plot(lambda, quantalEfficiencies(:,cMosaic.SCONE_ID), 'b-',  'LineWidth', 1.5);
    set(gca, 'XLim', xLims, 'XTick', xTicks);
    set(gca, 'YLim', yLims, 'YTick', yTicks);
    xlabel(gca, 'wavelength (nm)');
    ylabel(gca, 'axial absorbance');


    hFig = figure(12);
    plot(lambda, theConeMosaic.macular.transmittance, 'k-', 'LineWidth', 1.5);
    hold on;
    plot(lambda,  theLens.transmittance, 'k--', 'LineWidth', 1.5);
    legend({'macular pigment', 'lens'});
    set(gca, 'XLim', xLims, 'XTick', xTicks);
    %set(gca, 'YLim', yLims, 'YTick', yTicks);
    xlabel(gca, 'wavelength (nm)');
    ylabel(gca, 'transmittance');
    
end
